### ISSUE TITLE
getting blank screen in chat, group, contact fragments

### ISSUE THREAD

**Issue by ajith0001** [sumitdnath/SocialBlaze#2]
after generating apk when i run the app its showing blankly the fragments name only i want to create an chat app can u pls help me 
![Capturea](https://user-images.githubusercontent.com/60657136/73751795-cf28c700-4785-11ea-8eee-c8326758b503.JPG)
this is the ss of the page

**Comment by sumitdnath** [comment]
thanks for showing interest in this project. This Chat app is under development so it may take up to 2 week's from now to complete.
Thank you

**Comment by ajith0001** [comment]
Thank you @sumitdnath

**Comment by sumitdnath** [comment]
Hi @ajith0001 the app is now completed now you can download or copy the files
